// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package datasource

import (
	domain "github.com/ZupIT/charlescd/compass/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// FindAllDatasource is an autogenerated mock type for the FindAllDatasource type
type FindAllDatasource struct {
	mock.Mock
}

// Execute provides a mock function with given fields: workspaceId
func (_m *FindAllDatasource) Execute(workspaceId uuid.UUID) ([]domain.Datasource, error) {
	ret := _m.Called(workspaceId)

	var r0 []domain.Datasource
	if rf, ok := ret.Get(0).(func(uuid.UUID) []domain.Datasource); ok {
		r0 = rf(workspaceId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Datasource)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(workspaceId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
