// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package datasource

import (
	datasource "github.com/ZupIT/charlescd/compass/pkg/datasource"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// GetMetrics is an autogenerated mock type for the GetMetrics type
type GetMetrics struct {
	mock.Mock
}

// Execute provides a mock function with given fields: workspaceId
func (_m *GetMetrics) Execute(workspaceId uuid.UUID) (datasource.MetricList, error) {
	ret := _m.Called(workspaceId)

	var r0 datasource.MetricList
	if rf, ok := ret.Get(0).(func(uuid.UUID) datasource.MetricList); ok {
		r0 = rf(workspaceId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(datasource.MetricList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(workspaceId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
