// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package datasource

import (
	domain "github.com/ZupIT/charlescd/compass/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// SaveDatasource is an autogenerated mock type for the SaveDatasource type
type SaveDatasource struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *SaveDatasource) Execute(_a0 domain.Datasource) (domain.Datasource, error) {
	ret := _m.Called(_a0)

	var r0 domain.Datasource
	if rf, ok := ret.Get(0).(func(domain.Datasource) domain.Datasource); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(domain.Datasource)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Datasource) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
