// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package datasource

import (
	json "encoding/json"

	mock "github.com/stretchr/testify/mock"
)

// TestConnection is an autogenerated mock type for the TestConnection type
type TestConnection struct {
	mock.Mock
}

// Execute provides a mock function with given fields: pluginSrc, datasourceData
func (_m *TestConnection) Execute(pluginSrc string, datasourceData json.RawMessage) error {
	ret := _m.Called(pluginSrc, datasourceData)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, json.RawMessage) error); ok {
		r0 = rf(pluginSrc, datasourceData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
