dependencies:
- name: postgresql
  condition: postgresql.enabled
  version: "8.9.0"
- name: redis
  condition: redis.enabled
  version: "10.5.12"
- name: octopipe-charlescd
  condition: octopipe.enabled
  version: "1.0.4"
- name: envoy
  condition: envoy.enabled
  version: "0.3.10"
- name: keycloak
  condition: keycloak.enabled
  version: "7.5.8"
- name: ingress-nginx
  version: "3.15.2"
  repository: "https://kubernetes.github.io/ingress-nginx"
  condition: nginx_ingress_controller.enabled
- name: metacontroller
  conditon: metacontroller.enabled