apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6IHsicmVhbHdhdmVsYWIuYXp1cmVjci5pbyI6IHsiYXV0aCI6ICJjbVZoYkhkaGRtVnNZV0k2TDNWVk4xQkNlbGhHZWsxc2RteGlVVnBYVkVoUVFWQnhhak00YW1aTVZqRT0ifX19
kind: Secret
metadata:
  name: realwavelab-registry
type: kubernetes.io/dockerconfigjson