coverage:
  status:
    project:
      default:
        target: auto
      villager:
        target: 35%
        flags:
          - villager
      circlematcher:
        target: 70%
        flags:
          - circlematcher
      octopipe:
        target: 30%
        flags:
          - octopipe
      moove:
        target: 50%
        flags:
          - moove
      butler:
        target: 70%
        flags:
          - butler
      ui:
        target: 35%
        flags:
          - ui
    patch:
      default:
        only_pulls: true
      
flags:
  villager:
    paths:
      - villager/
    carryforward: true
  circlematcher:
    paths:
      - circle-matcher/
    carryforward: true
  octopipe:
    paths:
      - octopipe/
    carryforward: true
  moove:
    paths:
      - moove/
    carryforward: true
  butler:
    paths:
      - butler/
    carryforward: true
  ui:
    paths:
      - ui/
    carryforward: true

ignore:
  - ".github/**/*"
