coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        if_not_found: success
      
      villager:
        target: 30%
        flags:
          - villager
      
      circlematcher:
        target: 70%
        flags:
          - circlematcher
      
      octopipe:
        target: 30%
        flags:
          - octopipe
      
      moove:
        target: 50%
        flags:
          - moove
    
    patch:
      default:
        target: 80%
        threshold: 0%
        if_not_found: success
        
      villager:
        target: 30%
        flags:
          - villager
      
      circlematcher:
        target: 70%
        flags:
          - circlematcher
      
      octopipe:
        target: 30%
        flags:
          - octopipe
      
      moove:
        target: 50%
        flags:
          - moove

flags:
  villager:
    paths:
      - villager/
    carryforward: true
  
  circlematcher:
    paths:
      - circle-matcher/
    carryforward: true
  
  octopipe:
    paths:
      - octopipe/
    carryforward: true
  
  moove:
    paths:
      - moove/
    carryforward: true

ignore:
  - "docs/**/*"
  - ".github/**/*"
  - "images/**/*"
  - "butler/**/*"
  - "ui/**/*"
  - "tracing/**/*"
