coverage:
  status:
    change: off
    project:
       default:	
        target: auto	
        threshold: 0%
        if_not_found: success
        
      villager:
        target: 30%
        if_not_found: success
        flags:
          - villager
      
      circlematcher:
        target: 70%
        if_not_found: success
        flags:
          - circlematcher
      
      octopipe:
        target: 30%
        if_not_found: success
        flags:
          - octopipe
      
      moove:
        target: 50%
        if_not_found: success
        flags:
          - moove
      
      butler:
        target: 70%
        flags:
          - butler
      ui:
        target: 30%
        flags:
          - ui

    patch:
     default:	
        target: 80%
        if_not_found: success
        threshold: 0%

flags:
  villager:
    paths:
      - villager/src/main/java/
    carryforward: true
  
  circlematcher:
    paths:
      - circle-matcher/src/main/java/
    carryforward: true
  
  octopipe:
    paths:
      - octopipe/
    carryforward: true
  
  moove:
    paths:
      - moove/
    carryforward: true
    
  butler:
   paths:
     - butler/
   carryforward: true
   
  ui:
   paths:
     - ui/
   carryforward: true 

ignore:
  - "docs/**/*"
  - ".github/**/*"
  - "images/**/*"
  - "tracing/**/*"
