coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        flags: 
          - villager
          - circlematcher
          - octopipe
          - moove
          - butler
          - ui
      villager:
        target: 30%
        flags:
          - villager
      circlematcher:
        target: 70%
        flags:
          - circlematcher
      octopipe:
        target: 30%
        flags:
          - octopipe
      moove:
        target: 50%
        flags:
          - moove
      butler:
        target: 70%
        flags:
          - butler
      ui:
        target: 30%
        flags:
          - ui
    patch:
      default:
        target: 80%
        threshold: 0%
        flags: 
          - villager
          - circlematcher
          - octopipe
          - moove
          - butler
          - ui
      
flags:
  villager:
    paths:
      - villager/src/main/java/
    carryforward: true
  circlematcher:
    paths:
      - circle-matcher/src/main/java/
    carryforward: true
  octopipe:
    paths:
      - octopipe/
    carryforward: true
  moove:
    paths:
      - moove/
    carryforward: true
  butler:
    paths:
      - butler/
    carryforward: true
  ui:
    paths:
      - ui/
    carryforward: true

ignore:
  - ".github/**/*"
