coverage:
  status:
    project:
      default:
        target: auto
        threshold: 3%
        flags:
          - villager
          - circlematcher
          - octopipe
          - moove
          - ui
      villager:
        target: 35%
        flags:
          - villager
      circlematcher:
        target: 70%
        flags:
          - circlematcher
      octopipe:
        target: 30%
        flags:
          - octopipe
      moove:
        target: 50%
        flags:
          - moove
      ui:
        target: 35%
        flags:
          - ui
    patch:
      default:
        target: 80%
        threshold: 3%
        flags:
          - villager
          - circlematcher
          - octopipe
          - moove
          - ui

flags:
  villager:
    paths:
      - villager/
    carryforward: true
  circlematcher:
    paths:
      - circle-matcher/
    carryforward: true
  octopipe:
    paths:
      - octopipe/
    carryforward: true
  moove:
    paths:
      - moove/
    carryforward: true
  ui:
    paths:
      - ui/
    carryforward: true

ignore:
  - ".github/**/*"
  - "moove/infrastructure/src/main/kotlin/io/charlescd/moove/infrastructure/repository/**/*"
