coverage:
  status:
    project:
      default:
        target: 47%
        threshold: 3%
        flags: 
          - villager
          - circlematcher
          - octopipe
          - moove
          - butler
          - ui
    patch:
      default:
        target: 80%
        threshold: 3%
        flags: 
          - villager
          - circlematcher
          - octopipe
          - moove
          - butler
          - ui
      
flags:
  villager:
    paths:
      - villager/
    carryforward: true
  circlematcher:
    paths:
      - circle-matcher/
    carryforward: true
  octopipe:
    paths:
      - octopipe/
    carryforward: true
  moove:
    paths:
      - moove/
    carryforward: true
  butler:
    paths:
      - butler/
    carryforward: true
  ui:
    paths:
      - ui/
    carryforward: true

ignore:
  - ".github/**/*"
  - "moove/infrastructure/src/main/kotlin/io/charlescd/moove/infrastructure/repository/**/*"
  - "villager/src/main/java/io/charlescd/villager/infrastructure/persistence/**/*"
