coverage:  
  status:
    project:
      default:
        target: auto
        threshold: 0%
        only_pulls: true
        flags: 
          - villager
      villager:
        target: 30%
        flags: villager
    patch:
      default:
        target: 100%
        threshold: 1%
        only_pulls: true
        flags: 
          - villager
      villager:
        target: 100%
        flags: villager
flags:
  villager:
    paths:
      - villager/
