codecov:
  bot: ricardorames
  
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        flags: 
          - villager
          - circlematcher
      villager:
        target: 30%
        flags:
          - villager
      circle-matcher:
        target: 90%
        flags:
          - circlematcher
    patch:
      default:
        target: 100%
        threshold: 0%
        flags: 
          - villager
          - circlematcher
      
flags:
  villager:
    paths:
      - villager/
    carryforward: true
  circlematcher:
    paths:
      - circle-matcher/
    carryforward: true
