databaseChangeLog:
  - changeSet:
      id: 20200428150000-1
      author: adauto.paula
      comment: "Add threshold columns to components table"
      changes:
        - addColumn:
            tableName: components
            column:
              name: error_threshold
              type: integer
              constraints:
                nullable: false
        - addColumn:
            tableName: components
            column:
              name: latency_threshold
              type: integer
              constraints:
                nullable: false