databaseChangeLog:
  - changeSet:
      id: 20200716170000-1
      author: maycon.pacheco
      comment: "Add hostValue and gatewayName columns to components table"
      changes:
        - addColumn:
            tableName: components
            column:
              name: host_value
              type: varchar(255)
              constraints:
                nullable: true
        - addColumn:
            tableName: components
            column:
              name: gateway_name
              type: varchar(255)
              constraints:
                nullable: true
