databaseChangeLog:
  - changeSet:
      id: 20200717170000-1
      author: maycon.pacheco
      comment: "Add hostValue and gatewayName columns to components snapshot table"
      changes:
        - addColumn:
            tableName: component_snapshots
            column:
              name: host_value
              type: varchar(255)
              constraints:
                nullable: true
        - addColumn:
            tableName: component_snapshots
            column:
              name: gateway_name
              type: varchar(255)
              constraints:
                nullable: true
