databaseChangeLog:
  - changeSet:
      id: 20200508150500-1
      author: mateus.cruz
      comment: "Create table roles"
      changes:
        - createTable:
            tableName: roles
            columns:
              - column:
                  name: id
                  type: varchar(36)
                  autoIncrement: false
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: varchar(64)
                  constraints:
                    nullable: false
              - column:
                  name: description
                  type: text
                  constraints:
                    nullable: false
              - column:
                  name: created_at
                  type: timestamp
                  constraints:
                    nullable: false
