{{- if .Values.CharlesApplications.butler.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
  name: charlescd-butler-role-binding-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: charlescd-butler-role-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: charlescd-butler
  namespace: {{ .Release.Namespace }}
{{- end }}