{{- if .Values.CharlesApplications.butler.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: charlescd-butler-role-{{ .Release.Namespace }}
rules:
- apiGroups:
  - charlescd.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - patch
{{- end }}