---
apiVersion: v1
data:
  encryption-key: QzYzOUE1NzJFMTRENTA3NUM1MjZGRERENDNFNEVDRjZCMDk1RUExNzc4M0QzMkVGM0QyNzEwQUY5RjM1OURENA==
kind: Secret
metadata:
  name: deploy-aes256-key
type: Opaque
---
apiVersion: v1
data:
  encryption-key: NmRkZGU0MTAtM2YxYi0xMWViLWIzNzgtMDI0MmFjMTMwMDAy
kind: Secret
metadata:
  name: compass-aes256-key
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: application-aes256-key
type: Opaque
data:
  encryption-key: OGVhMzY4OGYtYmUxOS00YWU2LTljNmMtZDFhNjAzNjAyYTJm
---
{{- if .Values.CharlesApplications.hermes.enabled }}
apiVersion: v1
data:
  encryption-key: Yjg0NDVkMDUtMzliOC00YTkxLWEwOWMtZDRhN2VkOGRlZmRj
kind: Secret
metadata:
  name: hermes-aes256-key
type: Opaque
{{- end }}
---
apiVersion: v1
data:
  encryption-key: NjQ5NzE5MjNkMjFhNDg4N2EzYWNmMWFkMTU5NjFiYmM=
kind: Secret
metadata:
  name: gate-aes256-key
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: charlescd-rabbitmq-erl
data:
  rabbitmq-erlang-cookie: bWkyYVJyUnBFSldSQ05heW1hWWU3UTZWclYyRHVLcG8=
type: Opaque
---