---
apiVersion: v1
data:
  encryption-key: QzYzOUE1NzJFMTRENTA3NUM1MjZGRERENDNFNEVDRjZCMDk1RUExNzc4M0QzMkVGM0QyNzEwQUY5RjM1OURENA==
kind: Secret
metadata:
  name: deploy-aes256-key
type: Opaque
---
apiVersion: v1
data:
  encryption-key: NmRkZGU0MTAtM2YxYi0xMWViLWIzNzgtMDI0MmFjMTMwMDAy
kind: Secret
metadata:
  name: compass-aes256-key
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: application-aes256-key
type: Opaque
data:
  encryption-key: OGVhMzY4OGYtYmUxOS00YWU2LTljNmMtZDFhNjAzNjAyYTJm
---