{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ui.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.ui.name }}
    version: {{ .Values.ui.name }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.ui.name }}
      version: {{ .Values.ui.name }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: '{{ .Values.sidecarIstio.enabled }}' 
      labels:
        app: {{ .Values.ui.name }}
        version: {{ .Values.ui.name }}
    spec:
      containers:
        - name: {{ .Values.ui.name }}
          image: {{ .Values.ui.image.name }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP  
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1 
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          env:
            - name: REACT_APP_API_URI
              value: {{ .Values.ui.apiHost }}
            - name: REACT_APP_AUTH_URI
              value: {{ .Values.ui.keycloakHost }}
            - name: REACT_APP_AUTH_REALM
              value: charlescd
            - name: REACT_APP_AUTH_CLIENT_ID
              value: charlescd-client
          resources:
{{ toYaml .Values.ui.resources | indent 12 }}
    {{- with .Values.ui.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.ui.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.ui.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end}}
