apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: charlesroutes.charlescd.io
spec:
  group: charlescd.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                components:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      circles:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                            tag:
                              type: string
                            default:
                              type: boolean
                          required:
                            - id
                            - tag
                            - default
                    required:
                      - name
                      - circles
              required:
                - components
  names:
    kind: CharlesRoutes
    plural: charlesroutes
    singular: charlesroute
  scope: Namespaced
---
apiVersion: charlescd.io/v1
kind: CharlesRoutes
metadata:
  name: cluster-routes
spec:
  components: