#
# Copyright 2020, 2021 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
{{- if .Values.CharlesApplications.butler.enabled}}
apiVersion: v1
data:
  encryption-key: QzYzOUE1NzJFMTRENTA3NUM1MjZGRERENDNFNEVDRjZCMDk1RUExNzc4M0QzMkVGM0QyNzEwQUY5RjM1OURENA==
kind: Secret
metadata:
  name: deploy-aes256-key
type: Opaque
---
{{- end }}

{{- if .Values.CharlesApplications.compass.enabled }}
apiVersion: v1
data:
  encryption-key: NmRkZGU0MTAtM2YxYi0xMWViLWIzNzgtMDI0MmFjMTMwMDAy
kind: Secret
metadata:
  name: compass-aes256-key
type: Opaque
---
{{- end }}

{{- if or .Values.CharlesApplications.moove.enabled .Values.CharlesApplications.butler.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: application-aes256-key
type: Opaque
data:
  encryption-key: OGVhMzY4OGYtYmUxOS00YWU2LTljNmMtZDFhNjAzNjAyYTJm
---
{{- end }}

{{- if .Values.CharlesApplications.hermes.enabled }}
apiVersion: v1
data:
  encryption-key: Yjg0NDVkMDUtMzliOC00YTkxLWEwOWMtZDRhN2VkOGRlZmRj
kind: Secret
metadata:
  name: hermes-aes256-key
type: Opaque
---
{{- end }}

{{- if or .Values.CharlesApplications.moove.enabled .Values.CharlesApplications.gate.enabled }}
apiVersion: v1
data:
  encryption-key: NjQ5NzE5MjNkMjFhNDg4N2EzYWNmMWFkMTU5NjFiYmM=
kind: Secret
metadata:
  name: gate-aes256-key
type: Opaque
---
{{- end }}

{{- if .Values.rabbitmq.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: charlescd-rabbitmq-erl
data:
  rabbitmq-erlang-cookie: bWkyYVJyUnBFSldSQ05heW1hWWU3UTZWclYyRHVLcG8=
type: Opaque
---
{{- end }}
