apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
  name: charlescd-octopipe-role-binding-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: charlescd-octopipe-role-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: charlescd-octopipe
  namespace: {{ .Release.Namespace }}
