CREATE TABLE IF NOT EXISTS METRIC_EXECUTIONS (
	ID VARCHAR(36) PRIMARY KEY,
	METRIC_ID VARCHAR(36),
	LAST_VALUE REAL,
	STATUS VARCHAR(30),
	CREATED_AT TIMESTAMP DEFAULT clock_timestamp() NOT NULL,
	CONSTRAINT FK_METRIC_METRIC FOREIGN KEY(METRIC_ID) REFERENCES METRICS(ID) ON DELETE CASCADE
)