CREATE TABLE IF NOT EXISTS METRICS_GROUP (
	ID VARCHAR(36) PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	WORKSPACE_ID VARCHAR(36) NOT NULL,
	CIRCLE_ID VARCHAR(36) NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT clock_timestamp() NOT NULL
);

CREATE TABLE IF NOT EXISTS DATASOURCES (
	ID VARCHAR(36) PRIMARY KEY,
	PLUGIN_ID VARCHAR(50) NOT NULL,
	NAME VARCHAR(100) not null,
	CREATED_AT TIMESTAMP DEFAULT clock_timestamp() NOT NULL,
	DATA JSONB not NULL
);

CREATE TABLE IF NOT exists METRICS (
	ID VARCHAR(36) PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	THRESHOLD REAL not null,
	CONDITION VARCHAR(30) not null,
	metric_group_id varchar(36),
	datasource_id VARCHAR(36),
	created_at TIMESTAMP DEFAULT clock_timestamp() NOT NULL,
	CONSTRAINT fk_metric_group_metric FOREIGN KEY(metric_group_id) REFERENCES METRICS_GROUP(id),
	CONSTRAINT fk_metric_datasources FOREIGN KEY(datasource_id) REFERENCES DATASOURCES(id)
);

CREATE TABLE IF NOT EXISTS METRIC_FILTERS (
	ID VARCHAR(36) PRIMARY KEY,
	FIELD VARCHAR(100) NOT NULL,
	OPERATOR VARCHAR(30) not null,
	METRIC_ID varchar(36),
	CREATED_AT TIMESTAMP DEFAULT clock_timestamp() NOT NULL,
	CONSTRAINT fk_metric_metric_filter FOREIGN KEY(metric_id) REFERENCES METRICS(id)
);

CREATE TABLE IF NOT EXISTS METRIC_GROUPS_BY (
	ID VARCHAR(36) PRIMARY KEY,
	FIELD VARCHAR(100) NOT NULL,
	METRIC_ID varchar(36),
	CREATED_AT TIMESTAMP DEFAULT clock_timestamp() NOT NULL,
	CONSTRAINT fk_metric_metric_group_by FOREIGN KEY(metric_id) REFERENCES METRICS(id)
);
