CREATE TABLE IF NOT EXISTS ACTIONS_EXECUTIONS
(
    ID               VARCHAR(36) PRIMARY KEY,
    METRIC_ACTION_ID VARCHAR(36),
    STATUS           VARCHAR(30)                         NOT NULL,
    EXECUTION_LOG    TEXT,
    CREATED_AT       TIMESTAMP DEFAULT clock_timestamp() NOT NULL,
    STARTED_AT       TIMESTAMP DEFAULT clock_timestamp() NOT NULL,
    FINISHED_AT      TIMESTAMP DEFAULT clock_timestamp() NOT NULL,
    CONSTRAINT FK_METRIC_METRIC FOREIGN KEY (METRIC_ACTION_ID) REFERENCES METRICS_GROUP_ACTIONS (ID)
)
