version: "3"

services:
  postgres:
    image: postgres:11.8-alpine
    container_name: charles-gate-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=charles
      - POSTGRES_USER=charles
      - POSTGRES_PASSWORD=charles
      - MAX_CONNECTIONS=300
    networks:
      - development
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
networks:
  development:
    driver: bridge