// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	authorization "github.com/ZupIT/charlescd/gate/internal/use_case/authorization"
	mock "github.com/stretchr/testify/mock"
)

// DoAuthorization is an autogenerated mock type for the DoAuthorization type
type DoAuthorization struct {
	mock.Mock
}

// Execute provides a mock function with given fields: authorizationToken, workspaceId, input
func (_m *DoAuthorization) Execute(authorizationToken string, workspaceId string, input authorization.Input) error {
	ret := _m.Called(authorizationToken, workspaceId, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, authorization.Input) error); ok {
		r0 = rf(authorizationToken, workspaceId, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
