---
# Source: test/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test
    service: test
  name: test
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
    
  selector:
    app: test
  type: ClusterIP
---
# Source: test/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME
  namespace: default
  labels:
    app: test
    version: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
      version: RELEASE-NAME
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true' 
      labels:
        app: test
        version: RELEASE-NAME
    spec:
      containers:
        - name: test
          image: latest
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP  
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1 
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 128m
              memory: 128Mi
            requests:
              cpu: 64m
              memory: 64Mi
      imagePullSecrets:
        - name: realwavelab-registry
