---
apiVersion: v1
kind: Service
metadata:
  name: helm-test-chart
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: helm-test-chart
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-test-chart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-test-chart
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: helm-test-chart
          image: test/latest
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 128m
              memory: 128Mi
            requests:
              cpu: 64m
              memory: 64Mi
      imagePullSecrets:
        - name: realwavelab-registry
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: helm-test-chart
spec:
  serviceName: "helm-test-chart"
  replicas: 2
  selector:
    matchLabels:
      app: helm-test-chart
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: helm-test
          image: helm-test-image
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: www
              mountPath: /usr/share/helm-test/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi