import {
  COLOR_DODGER_BLUE,
  COLOR_MOUNTAIN_MEADOW,
  COLOR_VIOLET_BLUE,
  COLOR_ORANGE_PEEL,
  COLOR_RADICAL_RED,
  COLOR_SUMMER_SKY,
  COLOR_RED_ORANGE,
  COLOR_MAYA_BLUE,
  COLOR_GOLD,
  COLOR_CHRISTI,
  COLOR_MALACHITE
} from 'core/assets/colors';

export const light = {};

export const dark = {
  chartComparison: [
    COLOR_DODGER_BLUE,
    COLOR_MOUNTAIN_MEADOW,
    COLOR_VIOLET_BLUE,
    COLOR_ORANGE_PEEL,
    COLOR_RADICAL_RED,
    COLOR_SUMMER_SKY,
    COLOR_RED_ORANGE,
    COLOR_MAYA_BLUE,
    COLOR_GOLD,
    COLOR_CHRISTI
  ],
  chartError: COLOR_RED_ORANGE,
  chartLatency: COLOR_GOLD,
  chartRequestCircle: COLOR_MALACHITE
};
