export enum NotificationStatusEnum {

    SUCCEEDED = 'SUCCEEDED',
    FAILED = 'FAILED',
    FAILED_CONTINUE = 'FAILED_CONTINUE',
    SKIPPED = 'SKIPPED',
    TERMINAL = 'TERMINAL',
    UNDEPLOYED = 'UNDEPLOYED',
    UNDEPLOY_FAILED = 'UNDEPLOY_FAILED'
}
