apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: charlesroutes.zupit.com
spec:
  group: zupit.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                circles:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      components:
                        type: array
                        items:
                          type: string
                    required:
                      - id
                      - components
              required:
                - circles
  names:
    kind: CharlesRoute
    plural: charlesroutes
    singular: charlesroute
  scope: Namespaced
