apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: charlescd-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: zupit.com/v1
    resource: charlesdeployments # crd this controller is watching
  childResources:
  - apiVersion: v1
    resource: pods
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      webhook:
        url: http://nodejs-hook.hello/deployments # butler url

