// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package metric

import (
	domain "github.com/ZupIT/charlescd/compass/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// CreateMetric is an autogenerated mock type for the CreateMetric type
type CreateMetric struct {
	mock.Mock
}

// Execute provides a mock function with given fields: metricsGroup
func (_m *CreateMetric) Execute(metricsGroup domain.Metric) (domain.Metric, error) {
	ret := _m.Called(metricsGroup)

	var r0 domain.Metric
	if rf, ok := ret.Get(0).(func(domain.Metric) domain.Metric); ok {
		r0 = rf(metricsGroup)
	} else {
		r0 = ret.Get(0).(domain.Metric)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Metric) error); ok {
		r1 = rf(metricsGroup)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
