// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package metric

import (
	domain "github.com/ZupIT/charlescd/compass/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// UpdateMetric is an autogenerated mock type for the UpdateMetric type
type UpdateMetric struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *UpdateMetric) Execute(_a0 domain.Metric) (domain.Metric, error) {
	ret := _m.Called(_a0)

	var r0 domain.Metric
	if rf, ok := ret.Get(0).(func(domain.Metric) domain.Metric); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(domain.Metric)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Metric) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
