export const DeploymentsConfigurationConstants = {

  DEFAULT_CIRCLE_HEADER_NAME: 'x-circle-id',

  SPINNAKER_CREATE_APPLICATION_JOB_TYPE: 'createApplication',

  SPINNAKER_CREATE_APPLICATION_DEFAULT_CLOUD: 'kubernetes',

  SPINNAKER_CREATE_APPLICATION_PORT: 80,

  SPINNAKER_CREATE_APPLICATION_DEFAULT_EMAIL: 'darwin@zup.com'
}
