---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: istio
  namespace: kube-system
spec:
  chart: istio
  repo: https://storage.googleapis.com/istio-release/releases/1.2.2/charts/
  targetNamespace: istio-system
  valuesContent: |-
    gateways:
      enabled: true
      istio-egressgateway:
        enabled: true
    global:
      controlPlaneSecurityEnabled: false
      disablePolicyChecks: false
      hub: docker.io/istio
      mtls:
        enabled: false
      outboundTrafficPolicy:
        mode: ALLOW_ANY
      proxy:
        includeInboundPorts: '*'
      tag: 1.2.2
    grafana:
      enabled: false
    istio_cni:
      enabled: false
    kiali:
      enabled: false
      createDemoSecret: true
    mixer:
      adapters:
        stdio:
          enabled: false
      policy:
        enabled: false
      telemetry:
        enabled: false
    prometheus:
      enabled: false
    sidecarInjectorWebhook:
      enabled: false
      rewriteAppHTTPProbe: false
    tracing:
      enabled: false
