// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SecurityFilterService is an autogenerated mock type for the SecurityFilterService type
type SecurityFilterService struct {
	mock.Mock
}

// Enforce provides a mock function with given fields: permission, path, method
func (_m *SecurityFilterService) Enforce(permission string, path string, method string) (bool, error) {
	ret := _m.Called(permission, path, method)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string, string) bool); ok {
		r0 = rf(permission, path, method)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(permission, path, method)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
