// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "github.com/ZupIT/charlescd/gate/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// CreateSystemToken is an autogenerated mock type for the CreateSystemToken type
type CreateSystemToken struct {
	mock.Mock
}

// Execute provides a mock function with given fields: systemToken
func (_m *CreateSystemToken) Execute(systemToken domain.SystemToken) (domain.SystemToken, error) {
	ret := _m.Called(systemToken)

	var r0 domain.SystemToken
	if rf, ok := ret.Get(0).(func(domain.SystemToken) domain.SystemToken); ok {
		r0 = rf(systemToken)
	} else {
		r0 = ret.Get(0).(domain.SystemToken)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.SystemToken) error); ok {
		r1 = rf(systemToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
