// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "github.com/ZupIT/charlescd/gate/internal/domain"
	mock "github.com/stretchr/testify/mock"

	system_token "github.com/ZupIT/charlescd/gate/internal/use_case/system_token"
)

// CreateSystemToken is an autogenerated mock type for the CreateSystemToken type
type CreateSystemToken struct {
	mock.Mock
}

// Execute provides a mock function with given fields: authorization, input
func (_m *CreateSystemToken) Execute(authorization string, input system_token.CreateSystemTokenInput) (domain.SystemToken, error) {
	ret := _m.Called(authorization, input)

	var r0 domain.SystemToken
	if rf, ok := ret.Get(0).(func(string, system_token.CreateSystemTokenInput) domain.SystemToken); ok {
		r0 = rf(authorization, input)
	} else {
		r0 = ret.Get(0).(domain.SystemToken)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, system_token.CreateSystemTokenInput) error); ok {
		r1 = rf(authorization, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
