// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "github.com/ZupIT/charlescd/gate/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// GetAllSystemToken is an autogenerated mock type for the GetAllSystemToken type
type GetAllSystemToken struct {
	mock.Mock
}

// Execute provides a mock function with given fields: page
func (_m *GetAllSystemToken) Execute(page domain.Page) ([]domain.SystemToken, domain.Page, error) {
	ret := _m.Called(page)

	var r0 []domain.SystemToken
	if rf, ok := ret.Get(0).(func(domain.Page) []domain.SystemToken); ok {
		r0 = rf(page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SystemToken)
		}
	}

	var r1 domain.Page
	if rf, ok := ret.Get(1).(func(domain.Page) domain.Page); ok {
		r1 = rf(page)
	} else {
		r1 = ret.Get(1).(domain.Page)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(domain.Page) error); ok {
		r2 = rf(page)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
