// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "github.com/ZupIT/charlescd/gate/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// GetSystemToken is an autogenerated mock type for the GetSystemToken type
type GetSystemToken struct {
	mock.Mock
}

// Execute provides a mock function with given fields: id
func (_m *GetSystemToken) Execute(id uuid.UUID) (domain.SystemToken, error) {
	ret := _m.Called(id)

	var r0 domain.SystemToken
	if rf, ok := ret.Get(0).(func(uuid.UUID) domain.SystemToken); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.SystemToken)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
