// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "github.com/ZupIT/charlescd/gate/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// GetAllSystemToken is an autogenerated mock type for the GetAllSystemToken type
type GetAllSystemToken struct {
	mock.Mock
}

// Execute provides a mock function with given fields: page, size
func (_m *GetAllSystemToken) Execute(page int, size int) (domain.PageSystemToken, error) {
	ret := _m.Called(page, size)

	var r0 domain.PageSystemToken
	if rf, ok := ret.Get(0).(func(int, int) domain.PageSystemToken); ok {
		r0 = rf(page, size)
	} else {
		r0 = ret.Get(0).(domain.PageSystemToken)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(page, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
