// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// RevokeSystemToken is an autogenerated mock type for the RevokeSystemToken type
type RevokeSystemToken struct {
	mock.Mock
}

// Execute provides a mock function with given fields: id
func (_m *RevokeSystemToken) Execute(id uuid.UUID) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
