#!/bin/bash

# This hook prevent push of commits where not have DCO Signed Off

DUMMY_BASH=0000000000000000000000000000000000000000

echo "Running pre-push check;"
AUTHOR=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/\1/p')

while read local_ref local_sha remote_ref remote_sha
do
	if [ "$local_sha" = $DUMMY_BASH ]
	then
	echo "Branch deleted. Do nothing'"
    	  exit 0
	else
		RANGE="$remote_sha..$local_sha"

		echo "Verifing DCO signoff in commits'"
		SIGNED_OFF=$(git rev-list --no-merges --author "$AUTHOR" --grep "^Signed-off-by: " "$RANGE")
    NOT_SIGNED_OFF=$(git rev-list --no-merges --author "$AUTHOR" "$RANGE" | grep -Fxv "$SIGNED_OFF")

		if [ -n "$NOT_SIGNED_OFF" ]
		then
			echo >&2 "ERROR: Found commits do not have DCO Sign Off in $local_ref, not pushing."
			exit 1
		fi
	fi
done
exit 0