#!/bin/bash

# This hook prevent commits where not have license header
echo "Running pre-commit check;"

YEAR=$(date +'%Y')

FILES_WITHOUT_HEADER=()

echo "Getting changed files'"

CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR -- '*.ts' '*.go' '*.groovy' '*.java' '*.tsx' '*.kt' | sed 's| |\\ |g')

if [ -n "$CHANGED_FILES" ]
then
    echo "Checking for Copyright statement'"
    for FILE in $CHANGED_FILES; do
      FILES_WITHOUT_HEADER+=$(grep -L "Copyright 2020, $YEAR" "$CHANGED_FILES")
    done

    if [ -n "$FILES_WITHOUT_HEADER" ]
    then
        echo "Copyright 2020, $YEAR license header not found in some files."
        exit 1;
    fi
  fi
exit 0