DROP TABLE IF EXISTS SUBSCRIPTION_CONFIGURATION_EVENTS CASCADE;
DROP TABLE IF EXISTS SUBSCRIPTION_EVENTS CASCADE;
DROP TABLE IF EXISTS SUBSCRIPTIONS_EVENTS_EXECUTIONS CASCADE;
DROP TABLE IF EXISTS SUBSCRIPTIONS CASCADE;