DROP TABLE IF EXISTS PLUGINS CASCADE;
DROP TABLE IF EXISTS METRICS_GROUP CASCADE;
DROP TABLE IF EXISTS DATA_SOURCES CASCADE;
DROP TABLE IF EXISTS METRICS CASCADE;
DROP TABLE IF EXISTS METRIC_FILTERS CASCADE;
DROP TABLE IF EXISTS METRIC_GROUPS_BIES CASCADE;
