CREATE TABLE IF NOT EXISTS PLUGINS (
	ID VARCHAR(36) PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	SRC VARCHAR(100) NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT clock_timestamp() NOT NULL
);

ALTER TABLE DATA_SOURCES DROP COLUMN PLUGIN_SRC;

ALTER TABLE DATA_SOURCES ADD PLUGIN_ID VARCHAR(50);