#
  # Copyright 2020, 2021 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #  http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- if .Values.deploymentName }}
  name: {{ .Values.deploymentName }}
  {{- else }}
  name: {{ .Release.Name }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appname }}
    version: {{ .Release.Name }}
    component: {{ .Values.component }}
    tag: {{ .Values.tag }}
    circleId: {{ .Values.circleId }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appname }}
      version: {{ .Release.Name }}
      component: {{ .Values.component }}
      tag: {{ .Values.tag }}
      circleId: {{ .Values.circleId }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: '{{ .Values.istio.enabled }}'
      labels:
        app: {{ .Values.appname }}
        version: {{ .Release.Name }}
        component: {{ .Values.component }}
        tag: {{ .Values.tag }}
        circleId: {{ .Values.circleId }}
    spec:
      containers:
        - name: {{ .Values.service.name }}
          image: "{{ .Values.image.url }}"
          {{ if .Values.livenessProbe.enabled }}
          livenessProbe:
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
              scheme: {{ .Values.livenessProbe.httpGet.scheme }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          readinessProbe:
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
              scheme: {{ .Values.readinessProbe.httpGet.scheme }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          {{ end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{ if .Values.startcommand.enabled }}
          command: {{ .Values.startcommand.value }}
          {{ end }}
          env:
          {{ range $i, $var := .Values.envVars -}}
          - name: {{ $var.name | upper}}
            value: {{ $var.value | quote}}
          {{ end }}
          {{- if .Values.configmaps.enabled}}
          volumeMounts:
          {{ end }}
          {{ if .Values.configmaps.enabled }}
            - name: {{ .Release.Name }}-data
              mountPath: /data
          {{ end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
     {{ if .Values.configmaps.enabled }}
      volumes:
     {{ end }}
     {{ if .Values.configmaps.enabled }}
      - name: {{ .Release.Name }}-data
        configMap:
          name: {{ .Release.Name }}-data
          defaultMode: 0700
     {{ end }}
     {{- with .Values.nodeSelector }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
     {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}