// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package metrics_group

import (
	domain "github.com/ZupIT/charlescd/compass/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ListMetricGroupByCircle is an autogenerated mock type for the ListMetricGroupByCircle type
type ListMetricGroupByCircle struct {
	mock.Mock
}

// Execute provides a mock function with given fields: circleId
func (_m *ListMetricGroupByCircle) Execute(circleId uuid.UUID) ([]domain.MetricsGroupRepresentation, error) {
	ret := _m.Called(circleId)

	var r0 []domain.MetricsGroupRepresentation
	if rf, ok := ret.Get(0).(func(uuid.UUID) []domain.MetricsGroupRepresentation); ok {
		r0 = rf(circleId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MetricsGroupRepresentation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(circleId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
