export const NOTIFICATION_ACTION_TYPES = {
  LOADED_NOTIFICATIONS: 'NOTIFICATION/LOADED_NOTIFICATIONS',
  LOADED_NOTIFICATION: 'NOTIFICATION/LOADED_NOTIFICATION',
  GET_NOTIFICATIONS: 'NOTIFICATION/GET_NOTIFICATIONS',
  LOADING: 'NOTIFICATION/LOADING',
  SET_CONNECTED: 'NOTIFICATION/SET_CONNECTED',
  START_POLLING: 'NOTIFICATION/START_POLLING',
  STOP_POLLING: 'NOTIFICATION/STOP_POLLING',
}

export const notificationActions = {
  loadedNotifications: notifications => ({
    type: NOTIFICATION_ACTION_TYPES.LOADED_NOTIFICATIONS, notifications,
  }),
  loadedNotification: notification => ({
    type: NOTIFICATION_ACTION_TYPES.LOADED_NOTIFICATION, notification,
  }),
  getNotifications: id => ({
    type: NOTIFICATION_ACTION_TYPES.GET_NOTIFICATIONS, id,
  }),
  toggleLoading: () => ({ type: NOTIFICATION_ACTION_TYPES.LOADING }),
  setConnectStatus: status => ({ type: NOTIFICATION_ACTION_TYPES.SET_CONNECTED, status }),
  startPolling: authorId => ({ type: NOTIFICATION_ACTION_TYPES.START_POLLING, authorId }),
  stopPolling: () => ({ type: NOTIFICATION_ACTION_TYPES.STOP_POLLING }),
}
