// example of IRSA authentication https://aws.amazon.com/pt/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::example:role/example-name
  name: example-role
  namespace: example
