apiVersion: v1
kind: Pod
metadata:
  name: aws-pod-test-v9
  namespace: charles
spec:
  serviceAccountName: job-s3
  containers:
    - name: aws-pod-test
      image: zupcharles/matcher-s3-sync:latest
      imagePullPolicy: Always
      env:
        - name: WORKSPACE_ID
          value: 00000000-0000-0000-0000-0000000000000
        - name: MOOVE_URL
          value: http://charlescd-moove:8080
        - name: BUCKET_NAME
          value: example
        - name: CHARLES_USER
          value: example
        - name: CHARLES_PASS
          value: example
        - name: CHARLES_KEYCLOAK
          value: http://charlescd-keycloak-http:8080
        - name: PERIOD
          value: 10000
        - name: LIST_BUCKETS
          value: 0

