@Library('ZupSharedLibs@darwin') _

node {

  def projectName = "darwin-ui"

  try {

    switch (env.BRANCH_NAME) {

      case ~/PR-.*/:

        break

      default:
        buildWithMakefile {
          dockerRepositoryName = projectName
          dockerFileLocation = "."
          dockerBuildingImage = "${projectName}:builder"
          team = "Realwave"
          dockerk8sGroup = "darwin"
        }
        break
    }

  } catch (e) {

      notifyBuildStatus {
        buildStatus = "FAILED"
      }

      throw e
  }

}
