export const TAB = {
  DEFAULT: 'RELEASE',
  SEGMENTS: 'SEGMENTS',
  RELEASE: 'RELEASE',
  IMPORT_CSV: 'IMPORT_CSV',
}

export const RELEASE_MODE = {
  DEFAULT: 'CREATE',
  CREATE: 'CREATE',
  SEARCH: 'SEARCH',
}

export const SEGMENTS_TYPE = {
  MANUALLY: 'MANUALLY',
  IMPORT_CSV: 'IMPORT_CSV',
}

export const MATCHER_TYPE = {
  SIMPLE_KV: 'SIMPLE_KV',
  REGULAR: 'REGULAR',
}
