// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package action

import (
	domain "github.com/ZupIT/charlescd/compass/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// CreateAction is an autogenerated mock type for the CreateAction type
type CreateAction struct {
	mock.Mock
}

// Execute provides a mock function with given fields: datasource
func (_m *CreateAction) Execute(datasource domain.Action) (domain.Action, error) {
	ret := _m.Called(datasource)

	var r0 domain.Action
	if rf, ok := ret.Get(0).(func(domain.Action) domain.Action); ok {
		r0 = rf(datasource)
	} else {
		r0 = ret.Get(0).(domain.Action)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Action) error); ok {
		r1 = rf(datasource)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
