name: circles-sample dev-release

on:
  push:
    branches: [ release-darwin-* ]

jobs:
  build_and_push_prerelease:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.0.1
      with:
        path: ./samples/circles/app
        username: ${{secrets.DOCKER_REGISTRY_USERNAME}}
        password: ${{secrets.DOCKER_REGISTRY_PASSWORD}}
        registry: realwavelab.azurecr.io
        repository: circles-sample
        tag_with_ref: true
        tag_with_sha: false