name: circle-matcher prod-release

on:
  release:
    types:
      - created
    branches: [ master ]

jobs:
  build_and_push_prerelease:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('./circle-matcher/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Build with Maven
      working-directory: ./circle-matcher
      run: mvn -B clean install

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.0.1
      with:
        path: ./circle-matcher
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
        repository: zupcharles/charlescd-circle-matcher
        dockerfile: ./circle-matcher/Dockerfile
        tags: latest,${{ steps.get_version.outputs.VERSION }}
        tag_with_ref: false
        tag_with_sha: false