name: build hermes

on:
  push:
    branches: [main]
    paths:
      - "hermes/**"
    tags:
      - "!*"
  pull_request:
    branches: [ main, charlescd-release-*.0 ]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "hermes/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.15"

      - name: Run Unit tests
        working-directory: ./hermes
        run: |
          go test -v -coverpkg ./internal/... -coverprofile=coverage.cov ./internal/tests/...

      - name: Tests coverage
        uses: codecov/codecov-action@v1.0.13
        with:
          file: ./hermes/coverage.cov
          flags: hermes
          fail_ci_if_error: true

      - name: Code Style
        uses: docker://morphy/revive-action:v1
        with:
          config: ./hermes/revive.toml
          path: "./hermes/..."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Horusec Security
        working-directory: ./hermes
        run: |
          curl -fsSL https://horusec-cli.s3.amazonaws.com/install.sh | bash
          horusec start -p ./